# fly.toml app configuration file generated for skistore on 2023-07-14T10:46:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "skistore"
primary_region = "lhr"

[build]
  image = "eoinom/skistore:latest"

[env]
  ASPNETCORE_URLS="http://+8080"
  StripeSettings_PublishableKey="pk_test_51M46w1DcQBmeDzw8IuAQYLJ6GgzhUABRVa6JWj8kVcbZ2Y4ThjrM0otqEzW7QMh5LDqGUOQY5Co0O1vEJHILgRNi009enTgyKx"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
